name: deploy-google-cloud-secret
on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
    secrets:
      gcpCredentialsTest:
        required: true
      gcpCredentialsStage:
        required: true
      gcpCredentialsProd:
        required: true
      projectIdTest:
        required: true
      projectIdStage:
        required: true
      projectIdProd:
        required: true
      secretKey:
        required: true
jobs:
  test:
    environment: ${{ inputs.environmentName }}
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.gcpCredentialsTest }}
      PROJECT_ID: ${{ secrets.projectIdTest }}
      SECRET_KEY: ${{ secrets.secretKey }}_TEST
      SECRET_VALUE: ${{ secrets.TEST }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: delete secret
        continue-on-error: true
        run: 'gcloud secrets delete ${{ env.SECRET_KEY }}'

      - name: create secret
        run: 'printf "${{ env.SECRET_VALUE }}" | gcloud secrets create ${{ env.SECRET_KEY }} --data-file=-'
  stage:
    needs: test
    environment: ${{ inputs.environmentName }}
    if: ${{ github.event_name == 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.gcpCredentialsStage }}
      PROJECT_ID: ${{ secrets.projectIdStage }}
      SECRET_KEY: ${{ secrets.secretKey }}_STAGE
      SECRET_VALUE: ${{ secrets.STAGE }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: delete secret
        continue-on-error: true
        run: 'gcloud secrets delete ${{ env.SECRET_KEY }}'

      - name: create secret
        run: 'printf "${{ env.SECRET_VALUE }}" | gcloud secrets create ${{ env.SECRET_KEY }} --data-file=-'
  prod:
    needs: stage
    environment: ${{ inputs.environmentName }}
    if: ${{ github.event_name == 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.gcpCredentialsProd }}
      PROJECT_ID: ${{ secrets.projectIdProd }}
      SECRET_KEY: ${{ secrets.secretKey }}_PROD
      SECRET_VALUE: ${{ secrets.PROD }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: delete secret
        continue-on-error: true
        run: 'gcloud secrets delete ${{ env.SECRET_KEY }} --quiet'
      - name: create secret
        run: 'printf "${{ env.SECRET_VALUE }}" | gcloud secrets create ${{ env.SECRET_KEY }} --data-file=-'
