name: deploy-google-cloud-pubsub-topic-vnext
on:
  workflow_call:
    inputs:
      messageEnconding:
        required: true
        type: string
      schemaFile:
        required: true
        type: string
    secrets:
      gcpCredentials:
        required: true
      projectId:
        required: true
      topicName:
        required: true
jobs:
  topic:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.projectId }}
      GCP_CREDENTIALS: ${{ secrets.gcpCredentials }}
      TOPIC_NAME: ${{ secrets.topicName }}
      MESSAGE_ENCODING: ${{ inputs.messageEnconding }}
      SCHEMA_NAME: ${{ secrets.topicName }}      
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: delete topic
        uses: actions-hub/gcloud@master
        continue-on-error: true
        env:
          PROJECT_ID: ${{ env.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ env.GCP_CREDENTIALS }}
        with:
          args: pubsub topics delete ${{ env.TOPIC_NAME }}
      - name: deploy topic
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ env.GCP_CREDENTIALS }}
        with:
          args: pubsub topics create ${{ env.TOPIC_NAME }} --message-encoding=${{ env.MESSAGE_ENCODING }} --schema=${{ env.SCHEMA_NAME }}
