name: deploy-google-cloud-function
on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      environmentName:
        required: true
        type: string
      functionName:
        required: true
        type: string
      nugetConfig:
        required: true
        type: string
      nugetUserName:
        required: true
        type: string
      projectName:
        required: true
        type: string
      solutionFolder:
        required: true
        type: string
    secrets:
      gcpCredentials:
        required: true
      projectId:
        required: true
      subTopicName:
        required: true
      appSettingsJson:
        required: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: configure appsettings.json
        run: |
          echo ${{ secrets.appSettingsJson }} > ${{ inputs.solutionFolder }}/${{ inputs.projectName }}/appsettings.json
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ inputs.nugetUserName }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ inputs.nugetConfig }}) > ${{ inputs.solutionFolder }}/${{ inputs.projectName }}/nuget.config
          cp ${{ inputs.solutionFolder }}/${{ inputs.projectName }}/nuget.config ${{ inputs.solutionFolder }}/${{ inputs.projectName }}.Tests/nuget.config
      - name: build
        run: dotnet build ${{ inputs.solutionFolder }}/${{ inputs.projectName }}.sln --configuration "${{ inputs.config }}"
      - name: test
        run: dotnet test ${{ inputs.solutionFolder }}/${{ inputs.projectName }}.sln --configuration "${{ inputs.config }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.gcpCredentials }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ inputs.functionName }}
          runtime: dotnet3
          project_id: ${{ inputs.projectId }}
          source_dir: ${{ inputs.solutionFolder }}/${{ inputs.projectName }}
          entry_point: ${{ inputs.projectName }}.Function
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ secrets.projectId }}/topics/${{ secrets.subTopicName }}