name: deploy-google-cloud-secret
on:
  workflow_call:
    secrets:
      gcpCredentialsTest:
        required: true
      gcpCredentialsStage:
        required: true
      gcpCredentialsProd:
        required: true
      projectIdTest:
        required: true
      projectIdStage:
        required: true
      projectIdProd:
        required: true
      secretKey:
        required: true
      secretValue:
        required: true
jobs:
  test:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.gcpCredentialsTest }}
      PROJECT_ID: ${{ secrets.projectIdTest }}
      SECRET_KEY: ${{ secrets.secretKey }}
      SECRET_VALUE: ${{ secrets.secretValue }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: delete secret
        continue-on-error: true
        run: 'gcloud secrets delete ${{ env.SECRET_KEY }}'

      - name: create secret
        run: 'printf "${{ env.SECRET_VALUE }}" | gcloud secrets create ${{ env.SECRET_KEY }} --data-file=-'
