name: iam-service-account
on:
  workflow_call:
    inputs:
      addServiceAccountRole:
        required: false
        type: boolean
        default: true
    secrets:
      gcpCredentials:
        required: true
      projectId:
        required: true
      serviceAccountName:
        required: true
      roleName:
        required: true
jobs:
  serviceAccount:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcpCredentials }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: deploy service account
        run: 'gcloud iam service-accounts create ${{ secrets.serviceAccountName }}'
        continue-on-error: true
      - name: add custom role
        run: 'gcloud projects add-iam-policy-binding ${{ secrets.projectId }} --member="serviceAccount:${{ secrets.serviceAccountName }}@${{ secrets.projectId }}.iam.gserviceaccount.com" --role="projects/${{ secrets.projectId }}/roles/${{ secrets.roleName }}"'
      - name: add service account role
        run: 'gcloud projects add-iam-policy-binding ${{ secrets.projectId }} --member="serviceAccount:${{ secrets.serviceAccountName }}@${{ secrets.projectId }}.iam.gserviceaccount.com" --role="roles/iam.serviceAccountUser"'
        continue-on-error: true