name: iam-service-account
on:
  workflow_call:
    inputs:
    secrets:
      gcpCredentials:
        required: true
      projectId:
        required: true
      serviceAccountName:
        required: true  
  jobs:
    serviceAccount:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcpCredentials }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: deploy service account
        run: 'gcloud iam service-accounts create ${{ secrets.serviceAccountName }}'
